preload = ~/.config/hypr/wallpaper.jpg

wallpaper {
    monitor = eDP-1
    path =~/.config/hypr/wallpaper.jpg 
}

wallpaper {
    monitor =   HDMI-A-1
    path =~/.config/hypr/wallpaper.jpg 
}



wallpaper {
    monitor = DP-2
    path =~/.config/hypr/wallpaper.jpg 
}


#preload = ~/downloads/od_space02.png
#wallpaper = eDP-1, ~/Downloads/od_space02.png
#wallpaper = DP-2, ~/Downloads/od_space02.png
splash = false
ipc = off
